### ISSUE TITLE
image generated by sdxl has no alpha channel

### ISSUE THREAD

**Issue by SchumannTian** [rootonchair/diffuser_layerdiffuse#1]
thanks for your code!
I'm confused that the image generated using _test_diffusers_fg_only_sdxl.py_ has no alpha channel, while the image generated by _test_diffusers_fg_only.py_ has alpha channel. didn't figure out the reason...

**Comment by jaebbb** [comment]
same here. first is test_diffusers_fg_only_sdxl.py output and second is test_diffusers_fg_only.py output
![result_sdxl](https://github.com/rootonchair/diffuser_layerdiffuse/assets/52495256/b30b46f5-a376-430d-a770-77244fab4d00)
![result1](https://github.com/rootonchair/diffuser_layerdiffuse/assets/52495256/95f17171-cde9-4e10-a19e-4c93ddaf61b0)

**Comment by SchumannTian** [comment]
actually the image generated by sdxl is also with alpha channel, if you save the png[0] here(https://github.com/rootonchair/diffuser_layerdiffuse/blob/3b77ed4317790d2dcc2318702a5b7364e3443102/models.py#L280).

**Comment by SchumannTian** [comment]
this issue can be solved by adding add_watermarker=False in StableDiffusionXLPipeline.from_pretrained()
