### ISSUE TITLE
how to load background-conditioned foreground model?

### ISSUE THREAD

**Issue by weihaoxie** [rootonchair/diffuser_layerdiffuse#2]

**Comment by rootonchair** [comment]
Hi @weihaoxie, currently background-conditioned have not been supported. I will work on that as soon as possible

**Comment by nighting0le01** [comment]
hi how can we support foreground conditioned background generation

**Comment by rootonchair** [comment]
Foreground and Background conditioned generation have been supported now. I will push some more updates about foreground and background prompt separately as well as SDXL version
