### ISSUE TITLE
Is the latest version of diffusers supported?

### ISSUE THREAD

**Issue by Honey-666** [rootonchair/diffuser_layerdiffuse#3]
hi!
When I tried to use diffusers==0.29.0 it gave me an error, but 0.28.0 is fine, does it not support the latest version?

**Comment by rootonchair** [comment]
Hi @Honey-666 , could you help me providing the error message and your use case? Maybe the latest version changes broke something

**Comment by Honey-666** [comment]
> Hi @Honey-666 , could you help me providing the error message and your use case? Maybe the latest version changes broke something

When I upgrade diffusers to 0.29.0 or later and run `test_diffusers_fg_only_sdxl.py`, he throws a `RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same` exception

`diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py", line 1289, in __call__
image = self.vae.decode(latents, return_dict=False)[0]`

**Comment by rootonchair** [comment]
Hi @Honey-666 , in 0.29.0 has some breaking changes. You can temporary fix this error by disable `force_upcase=False`
````python
transparent_vae = TransparentVAEDecoder.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16).to("cuda")
    transparent_vae.config.force_upcast = False
````

**Comment by Honey-666** [comment]
> > Hi @Honey-666 , in 0.29.0 has some breaking changes that made reading the config inaccurately. You can temporary fix this error by disable `force_upcase=False`
> > ```python
> > transparent_vae = TransparentVAEDecoder.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16).to("cuda")
> > transparent_vae.config.force_upcast = False
> > ```
> 
> Ok! Thank you for your reply. `transparent_vae.config.force_upcast = False` Does this mean that it is not converted to float32?

**Comment by rootonchair** [comment]
Yes, because we have used the vae "madebyollin/sdxl-vae-fp16-fix" that fix fp16 overflow issue in SDXL's VAE. So convert to fp32 during VAE inference is no needed

**Comment by Honey-666** [comment]
> Yes, because we have used the vae `"madebyollin/sdxl-vae-fp16-fix"` that fix fp16 overflow issue in SDXL's VAE. So convert to fp32 during VAE inference is no needed

Thanke you!
