### ISSUE TITLE
support img2img?

### ISSUE THREAD

**Issue by MikeHanKK** [rootonchair/diffuser_layerdiffuse#4]
webui version has upgraded the img2img function. Can this port update as well? 
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/854

@rootonchair

**Comment by rootonchair** [comment]
@MikeHanKK I believe it can be updated in this port. But let me have a look first

**Comment by MikeHanKK** [comment]
@rootonchair any progress on this?

**Comment by elismasilva** [comment]
@rootonchair i tried do this work to image to image, but when i provide transparent image it is not working, image appears all in red. I tried bring the code but i dont have much experience handling images.

**Comment by rootonchair** [comment]
Hi, img2img has been supported. You can check out here: https://github.com/rootonchair/diffuser_layerdiffuse/blob/main/test_diffusers_fg_only_sdxl_img2img.py
